### ISSUE TITLE
feat: Integrate "Initiative" PDF into cloud

### ISSUE THREAD

**Issue by jonarivado** [project-owlly/cloud#44]
The needed JS Code for pdfkit is in `pdf1.js`, fonts and images are in the zip file as well.

[generatePdf.zip](https://github.com/project-owlly/cloud/files/5361354/generatePdf.zip)

**Comment by peterpeterparker** [comment]
Thx 👍

**Comment by sansan88** [comment]
@peterpeterparker 
Can you implement this next week?

**Comment by peterpeterparker** [comment]
Next week maybe no. Following week I can have a look.

**Comment by sansan88** [comment]
Also ok for me :)

**Comment by sansan88** [comment]
What are you planning to do next week? I'm on holiday till Thursday.

**Comment by peterpeterparker** [comment]
Next week I've got nothing on the agenda for Owlly. What we discussed, beside storage, was  done.

**Comment by sansan88** [comment]
Ok good! Then you can use your time for other projects and we plan our next milestone after next week?

**Comment by peterpeterparker** [comment]
There  is the call next Friday, we can discuss what to do there or after the call.

**Comment by sansan88** [comment]
Good point!

**Comment by peterpeterparker** [comment]
@jonarivado @sansan88 PDF is integrated in the cloud but the output isn't 100% what I expected, it generates 4 pages instead of 1. But, beside this, it seems alright, it is generated, fonts and images are there.

That's why I assigned the task to Jonathan so you can try to debug what's wrong.

You can print out the PDF using following link:

https://europe-west6-project-owlly.cloudfunctions.net/generatePDF/1234

The source code is in pdf.utils.ts:

https://github.com/project-owlly/cloud/blob/master/functions/src/request/pdf/utils/pdf.utils.ts

**Comment by sansan88** [comment]
thank you david! I need to go to bed now...
@jonarivado , do you have time to have a look on this?

**Comment by sansan88** [comment]
keep in mind to changes this back when its working
https://github.com/project-owlly/cloud/pull/50#issuecomment-712912215

**Comment by sansan88** [comment]
I started to debug.. some methods are in a wrong order.. 
I will fix it with branch: pdflayout

**Comment by sansan88** [comment]
https://europe-west6-project-owlly.cloudfunctions.net/generatePDF/123
looks much better now..

**Comment by peterpeterparker** [comment]
@sansan88 I don't notice any changes

**Comment by sansan88** [comment]
seems my temp deployment to functions is overwritten by the actions deployment

**Comment by sansan88** [comment]
check again!
or checkout the pdflayout branch

**Comment by peterpeterparker** [comment]
way better 👍
